on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and package assets
        run: go build -v ./... -o gorf

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: gorf